server:
  port: 8084

spring:
  application:
    name: order-service
  
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# 외부 서비스 URL (Product Service 연동)
external:
  product-service:
    url: http://localhost:8083/api/products
  user-service:
    url: http://localhost:8082/api/users

logging:
  level:
    shb.gpark.orderservice: DEBUG 